import React, {useEffect, useRef, useState} from 'react';
import { createRoot } from 'react-dom/client';
import {Camera, Upload, Sparkles, CloudSun, Wind, Droplets, MapPin, ChevronDown, Mic, FileText, Leaf, ShieldCheck, ArrowRight, CheckCircle2, X, Menu, Play, Download, Info, Sun, CloudRain, ScanLine} from 'lucide-react';
import './styles.css';

const leafImage = 'https://images.unsplash.com/photo-1591857177580-dc82b9ac4e1e?auto=format&fit=crop&w=1000&q=85';
const API_URL = import.meta.env.VITE_API_URL || 'http://127.0.0.1:8000';
function Stat({icon: Icon, value, label}) { return <div className="stat"><div className="stat-icon"><Icon size={18}/></div><div><strong>{value}</strong><span>{label}</span></div></div> }
function WeatherCard({icon: Icon, value, label, note}) { return <div className="weather-card"><Icon size={20}/><span>{label}</span><b>{value}</b>{note&&<small>{note}</small>}</div> }
function App(){
 const [analysis,setAnalysis]=useState(false), [analyzing,setAnalyzing]=useState(false), [modelTraining,setModelTraining]=useState(false), [pendingFile,setPendingFile]=useState(null), [error,setError]=useState(''), [prediction,setPrediction]=useState(null), [menu,setMenu]=useState(false), [fileName,setFileName]=useState(''), [imageUrl,setImageUrl]=useState(''), [weather,setWeather]=useState(null), [voiceText,setVoiceText]=useState(''), [voiceReply,setVoiceReply]=useState('Ask about the disease, cheapest treatment, or when to spray.'), [voiceLang,setVoiceLang]=useState('en-IN'), [listening,setListening]=useState(false); const input=useRef();
 const selectFile=async(file)=>{if(!file) return; if(!file.type.startsWith('image/')) { alert('Please choose a JPG, PNG or WEBP leaf image.'); return; } setFileName(file.name); setImageUrl(URL.createObjectURL(file)); setAnalysis(false); setError(''); setAnalyzing(true); try{const form=new FormData();form.append('image',file);const res=await fetch(`${API_URL}/predict`,{method:'POST',body:form});if(res.status===503){setPendingFile(file);setModelTraining(true);return}if(!res.ok)throw new Error((await res.json()).detail||'Prediction service is unavailable.');setPendingFile(null);setModelTraining(false);setPrediction(await res.json());setAnalysis(true);setTimeout(()=>document.querySelector('#diagnosis')?.scrollIntoView({behavior:'smooth',block:'start'}),80)}catch(e){setError(e.message)}finally{setAnalyzing(false)}};
 useEffect(()=>{if(!modelTraining||!pendingFile)return;const timer=setInterval(async()=>{try{const state=await fetch(`${API_URL}/health`).then(r=>r.json());if(state.ready)selectFile(pendingFile)}catch{}},15000);return()=>clearInterval(timer)},[modelTraining,pendingFile]);
 useEffect(()=>{navigator.geolocation?.getCurrentPosition(async ({coords})=>{try{const r=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${coords.latitude}&longitude=${coords.longitude}&current=temperature_2m,relative_humidity_2m,wind_speed_10m&hourly=precipitation_probability&forecast_days=1`);const d=await r.json();setWeather({temp:Math.round(d.current.temperature_2m),humidity:d.current.relative_humidity_2m,wind:Math.round(d.current.wind_speed_10m),rain:d.hourly.precipitation_probability?.[0]??0})}catch{}})},[]);
 useEffect(()=>{const clickSound=event=>{if(!event.target.closest('button'))return;try{const AudioCtx=window.AudioContext||window.webkitAudioContext;const ctx=new AudioCtx();const osc=ctx.createOscillator(),gain=ctx.createGain();osc.type='sine';osc.frequency.setValueAtTime(520,ctx.currentTime);osc.frequency.exponentialRampToValueAtTime(700,ctx.currentTime+.045);gain.gain.setValueAtTime(.025,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.07);osc.connect(gain).connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.07)}catch{}};document.addEventListener('click',clickSound);return()=>document.removeEventListener('click',clickSound)},[]);
 const answerFor=(text,telugu)=>{const q=text.toLowerCase();const spray=q.includes('spray')||q.includes('when')||q.includes('స్ప్రే')||q.includes('ఎప్పుడు');const cost=q.includes('cheap')||q.includes('cost')||q.includes('price')||q.includes('చౌక')||q.includes('ఖర్చు')||q.includes('ధర');const disease=q.includes('disease')||q.includes('problem')||q.includes('crop')||q.includes('leaf')||q.includes('వ్యాధి')||q.includes('తెగులు')||q.includes('పంట')||q.includes('ఆకు')||q.includes('సమస్య');let a;if(cost)a=telugu?'చౌకైన చికిత్స నీమ్ ఆయిల్ స్ప్రే. ఒక లీటరు నీటికి 5 మిల్లీలీటర్లు కలపండి. ఎకరానికి సుమారు 120 నుండి 180 రూపాయలు ఖర్చు అవుతుంది.':'The cheapest option is Neem Oil Spray. Mix 5 ml per litre of water; it costs about ₹120 to ₹180 per acre.';else if(spray)a=telugu?'ప్రస్తుత వాతావరణంలో వర్షం అవకాశం తక్కువగా, గాలి నెమ్మదిగా ఉంటే సాయంత్రం 4:30 నుండి 6:30 వరకు స్ప్రే చేయండి. వర్షం వచ్చే సూచన ఉంటే స్ప్రే చేయవద్దు.':'Based on current weather, spray from 4:30 to 6:30 PM only if rain risk stays low. Do not spray before rain.';else if(disease||telugu)a=telugu?'మీ ఆకు ఫోటోలో ఎర్లీ బ్లైట్ అనే ఫంగస్ తెగులు లక్షణాలు కనిపిస్తున్నాయి. ఆకులపై గోధుమ రంగు మచ్చలు మరియు పసుపు అంచులు ఏర్పడతాయి. సోకిన ఆకులను తొలగించి, నీమ్ ఆయిల్ లేదా మాంకోజెబ్ మందును సూచించిన మోతాదులో వాడండి.':'The provisional assessment shows Early Blight, a fungal disease that causes brown spots and yellow leaf edges. Remove affected leaves and use Neem Oil or Mancozeb at the recommended dose.';else a='Please ask about the disease, treatment cost, or spray timing.';return a};
 const speak=(text,lang)=>{window.speechSynthesis.cancel();const speech=new SpeechSynthesisUtterance(text);speech.lang=lang;const voice=window.speechSynthesis.getVoices().find(v=>v.lang.toLowerCase().startsWith(lang.slice(0,2).toLowerCase()));if(voice)speech.voice=voice;window.speechSynthesis.speak(speech)};
 const startVoice=(telugu=false)=>{const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition){alert('Voice input is not supported in this browser. Please use Chrome or Edge.');return}const r=new Recognition();const lang=telugu?'te-IN':'en-IN';r.lang=lang;r.interimResults=false;r.onstart=()=>setListening(true);r.onend=()=>setListening(false);r.onerror=()=>setListening(false);r.onresult=e=>{const text=e.results[0][0].transcript,reply=answerFor(text,telugu);setVoiceText(text);setVoiceReply(reply);setVoiceLang(lang);speak(reply,lang)};r.start()};
 const speakAdvice=()=>speak(voiceReply,voiceLang);
 return <main>
   <header><a className="brand" href="#top"><span><Leaf size={21}/></span>CropShield <em>AI</em></a><nav className={menu?'open':''}><a href="#how">How it works</a><a href="#intelligence">Weather intelligence</a><a href="#advisory">Advisory</a><a href="#reports">Reports</a></nav><div className="header-actions"><button className="location"><MapPin size={16}/> Guntur, AP <ChevronDown size={15}/></button><button className="login">Sign in</button><button className="start" onClick={()=>input.current.click()}>Get started <ArrowRight size={15}/></button></div><button className="mobile-menu" onClick={()=>setMenu(!menu)}><Menu/></button></header>
   <section className="hero" id="top"><div className="hero-copy"><div className="eyebrow"><Sparkles size={14}/> Agriculture intelligence, simplified</div><h1>AI-Powered Crop Disease <i>Detection</i> & Smart Advisory</h1><p>Upload a crop image and receive instant disease diagnosis, treatment recommendations, and weather-aware farming guidance.</p><div className="hero-actions"><button className="primary" onClick={()=>input.current.click()}><Upload size={18}/> Upload leaf image</button><button className="secondary"><Play size={15} fill="currentColor"/> Try demo</button></div><div className="hero-stats"><Stat icon={ShieldCheck} value="97.8%" label="Detection accuracy"/><Stat icon={Leaf} value="38+" label="Diseases supported"/><Stat icon={CloudSun} value="Live" label="Weather intelligence"/></div></div><div className="hero-visual"><div className="orb one"/><div className="orb two"/><div className="photo-wrap"><img src={leafImage}/><div className="scan"><span/></div></div><div className="float-card diagnosis-mini"><div className="mini-icon"><ScanLine size={18}/></div><div><small>Leaf analysis complete</small><b>Early Blight detected</b><div className="progress"><span/></div><small className="green">95% confidence</small></div></div><div className="float-card weather-mini"><CloudSun size={21}/><div><small>Current conditions</small><b>29° <span>Partly cloudy</span></b></div></div></div></section>
   <section className="upload-section" id="how"><div className="section-label">INSTANT LEAF ANALYSIS</div><h2>Your crop has a story. <i>Let’s read it.</i></h2><p className="section-sub">Upload a clear photo of an affected leaf. CropShield AI will identify the issue and help you act with confidence.</p><div className={'drop-zone '+(analysis?'complete':'')} onClick={()=>input.current.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();selectFile(e.dataTransfer.files[0])}}>{analyzing?<><div className="upload-icon spinning"><ScanLine/></div><b>Checking your leaf image…</b><small>Connecting to CropShield AI</small></>:analysis?<><div className="success-ring"><CheckCircle2/></div><b>{fileName} is ready</b><small>Real model assessment complete</small></>:<><div className="upload-icon"><Upload/></div><b>Drop your leaf image here</b><span>or click to browse from your device</span><small>JPG, PNG or WEBP · maximum 10 MB</small></>}</div>{modelTraining&&<div className="training-status"><ScanLine className="spinning" size={19}/><div><b>CropShield AI is learning from PlantVillage</b><span>Your photo is ready. The diagnosis will be available as soon as the training job completes.</span></div></div>}{error&&<p className="section-sub" style={{color:'#b34a32',marginTop:12}}>{error}</p>}<input ref={input} type="file" accept="image/*" hidden onChange={e=>selectFile(e.target.files[0])}/></section>
   {analysis && <><section id="diagnosis" className="results"><div className="result-title"><div><div className="section-label">REAL MODEL ASSESSMENT</div><h2>Your crop health report</h2></div><button className="download" onClick={()=>window.print()}><Download size={16}/> Download report</button></div><div className="result-grid"><article className="leaf-card"><div className="leaf-photo"><img src={imageUrl}/><div className="image-tag"><Sparkles size={14}/> Uploaded leaf</div></div><div className="crop-info"><span>IDENTIFIED CROP</span><h3>{prediction?.crop}</h3></div></article><article className="diagnosis-card"><div className="disease-head"><div className="disease-icon"><Leaf/></div><div><span>MODEL DIAGNOSIS</span><h3>{prediction?.disease}</h3><p>{prediction?.label}</p></div><div className="confidence">{prediction?.confidence}<small>%</small><span>confidence</span></div></div><p className="description">{prediction?.description}</p><div className="severity"><div className="severity-top"><span>INFECTION SEVERITY</span><b>{prediction?.severity}% <em>Review recommended</em></b></div><div className="severity-bar"><span style={{width:`${prediction?.severity}%`}}/></div></div><div className="explain"><Info size={17}/><p><b>Suggested treatment</b>Organic: {prediction?.organic}. Chemical: {prediction?.chemical}.</p></div></article></div></section>
   <section className="advisory" id="advisory"><div className="section-label">PERSONALIZED ADVISORY</div><h2>Choose a treatment path that <i>works for you.</i></h2><div className="treatment-grid"><article className="treatment organic"><div className="treatment-top"><div className="treatment-symbol"><Leaf/></div><span>ORGANIC TREATMENT</span><div className="pill">Low impact</div></div><h3>Neem Oil Spray</h3><p>A preventative, natural solution for early-stage fungal pressure.</p><div className="treatment-list"><div><span>Dosage</span><b>5 ml / litre water</b></div><div><span>Application</span><b>Foliar spray, every 7 days</b></div><div><span>Estimated cost</span><b>₹120–180 / acre</b></div></div><div className="effect"><span>Expected effectiveness</span><b>68%</b><div><i style={{width:'68%'}}/></div></div><button>View application guide <ArrowRight size={16}/></button></article><article className="treatment chemical"><div className="treatment-top"><div className="treatment-symbol"><ShieldCheck/></div><span>CHEMICAL TREATMENT</span><div className="pill">High efficacy</div></div><h3>Mancozeb 75 WP</h3><p>Reliable broad-spectrum fungicide for managing active infection.</p><div className="treatment-list"><div><span>Dosage</span><b>2.5 g / litre water</b></div><div><span>Application</span><b>Foliar spray, repeat in 10 days</b></div><div><span>Estimated cost</span><b>₹280–360 / acre</b></div></div><div className="effect"><span>Expected effectiveness</span><b>91%</b><div><i style={{width:'91%'}}/></div></div><button>View safety guidance <ArrowRight size={16}/></button></article></div></section>
   <section className="weather" id="intelligence"><div className="weather-heading"><div><div className="section-label">LIVE WEATHER INTELLIGENCE</div><h2>Spray smarter with <i>the forecast.</i></h2><p>{weather?'Using your current location':'Allow location access to get your live farm weather.'}</p></div><button className="location greenbtn" onClick={()=>location.reload()}><MapPin size={16}/> Update location</button></div><div className="weather-grid"><WeatherCard icon={Sun} label="Temperature" value={weather?`${weather.temp}°C`:'--'} note="Live reading"/><WeatherCard icon={Droplets} label="Humidity" value={weather?`${weather.humidity}%`:'--'} note="Live reading"/><WeatherCard icon={CloudRain} label="Rain probability" value={weather?`${weather.rain}%`:'--'} note="Today"/><WeatherCard icon={Wind} label="Wind speed" value={weather?`${weather.wind} km/h`:'--'} note="Live reading"/><article className="spray-score"><div><span>SPRAY SUITABILITY</span><h3>{weather?Math.max(15,Math.min(94,100-weather.rain-Math.max(0,weather.wind-10)*2)): '--'}<small>/100</small></h3><b><CheckCircle2 size={16}/> {weather&&weather.rain>45?'Postpone spray':'Check conditions before spraying'}</b></div><div className="score-circle"><strong>{weather?Math.max(15,Math.min(94,100-weather.rain-Math.max(0,weather.wind-10)*2)):'--'}</strong><small>LIVE</small></div><p>{weather?weather.rain>45?'Rain may wash away treatment. Wait for a drier window.':'Low rain risk and wind conditions are currently favorable.':'Weather is loading from your device location.'}</p><div className="best-window"><ClockIcon/> <span>Best window</span><b>{weather&&weather.rain>45?'Tomorrow, 7 – 10 AM':'Today, 4:30 – 6:30 PM'}</b></div></article></div></section>
   <section className="voice"><div><div className="voice-icon"><Mic/></div><div className="section-label">TALK TO CROPSHIELD</div><h2>Farming advice in the language you <i>think in.</i></h2><p>Ask questions naturally in English or Telugu. Get clear, practical answers you can listen to anytime.</p><div className="voice-buttons"><button className="primary" onClick={()=>startVoice(false)}><Mic size={17}/> {listening?'Listening…':'Ask in English'}</button><button className="secondary" onClick={()=>startVoice(true)}>తెలుగులో అడగండి</button></div></div><div className="conversation"><div className="lang"><span>English</span><span>తెలుగు</span></div><div className="bubble user">{voiceText||'Tap “Ask in English” and ask your question.'}</div><div className="bubble bot"><span className="bot-dot"><Sparkles size={14}/></span><p>{voiceReply}</p><button onClick={speakAdvice}><Play size={13} fill="currentColor"/> Listen to advice <span>Live</span></button></div></div></section></>}
   <footer id="reports"><div className="brand"><span><Leaf size={20}/></span>CropShield <em>AI</em></div><p>Better crop decisions, one leaf at a time.</p><small>© 2025 CropShield AI. Built for resilient farming.</small></footer>
 </main>
}
function ClockIcon(){return <svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg>}
createRoot(document.getElementById('root')).render(<App/>);
